# Compile java file
build: HelloWorld.java
	javac HelloWorld.java
# Run compiled class
run: HelloWorld.class
	java HelloWorld
# Delete compiled class
clean: HelloWorld.class
	rm HelloWorld.class
# Mark targets as not filename
.PHONY: build run clean
